<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simple" nsURI="http://www.example.org/simple" nsPrefix="simple">
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//RuntimeState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootSteps" lowerBound="1"
        upperBound="-1" eType="#//RuntimeStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeExtensions" upperBound="-1"
        eType="#//RuntimeExtension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingSteps" upperBound="-1"
        eType="#//RuntimeStep" eOpposite="#//RuntimeStep/sourceState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endingSteps" upperBound="-1"
        eType="#//RuntimeStep" eOpposite="#//RuntimeStep/targetState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
        eType="#//RuntimeStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceState" lowerBound="1"
        eType="#//RuntimeState" eOpposite="#//RuntimeState/startingSteps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//RuntimeState"
        eOpposite="#//RuntimeState/endingSteps"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticRuleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticRuleTarget" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeValue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeIntegerValue" eSuperTypes="#//RuntimeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeReferenceValue" eSuperTypes="#//RuntimeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedObject" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeBooleanValue" eSuperTypes="#//RuntimeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeStringValue" eSuperTypes="#//RuntimeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeValues" lowerBound="1"
        upperBound="-1" eType="#//RuntimeValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedStaticElement"
        lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeContainmentValue" eSuperTypes="#//RuntimeValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeObject" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
